name: CI
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Release CV PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Generate PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Rename PDF
        run: mv main.pdf ozren_dabic_cv.pdf
      - name: Release PDF
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ozren_dabic_cv.pdf
